package AfkKiller;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * The GUI of a bloodpoint farming bot for Dead By Daylight
 * @author Netra14
 */
public class KillerUI extends javax.swing.JFrame {

    /**
     * Creates new form KillerUI
     */
    public KillerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        legacyPanel = new javax.swing.JPanel();
        legacyOutputField = new java.awt.TextArea();
        legacyInputField = new java.awt.TextField();
        legacyStartButton = new java.awt.Button();
        legacySendButton = new java.awt.Button();
        mainMenu = new javax.swing.JPanel();
        titleLabel = new java.awt.Label();
        outputField = new java.awt.TextArea();
        runButton = new java.awt.Button();
        instructionsPanel = new javax.swing.JPanel();
        instructionLabel = new java.awt.Label();
        settingsPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPane.setBackground(new java.awt.Color(100, 100, 100));

        legacyPanel.setBackground(new java.awt.Color(0, 0, 0));

        legacyOutputField.setBackground(new java.awt.Color(0, 0, 0));
        legacyOutputField.setEditable(false);
        legacyOutputField.setForeground(new java.awt.Color(0, 0, 250));
        legacyOutputField.setText(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");

        legacyInputField.setBackground(new java.awt.Color(0, 0, 100));
        legacyInputField.setForeground(new java.awt.Color(200, 200, 200));
        legacyInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legacyInputFieldActionPerformed(evt);
            }
        });

        legacyStartButton.setActionCommand("Start");
        legacyStartButton.setBackground(new java.awt.Color(0, 0, 0));
        legacyStartButton.setForeground(new java.awt.Color(0, 0, 255));
        legacyStartButton.setLabel("Start");
        legacyStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legacyStartButtonActionPerformed(evt);
            }
        });

        legacySendButton.setBackground(new java.awt.Color(0, 0, 0));
        legacySendButton.setForeground(new java.awt.Color(0, 0, 255));
        legacySendButton.setLabel("Send");
        legacySendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legacySendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout legacyPanelLayout = new javax.swing.GroupLayout(legacyPanel);
        legacyPanel.setLayout(legacyPanelLayout);
        legacyPanelLayout.setHorizontalGroup(
            legacyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(legacyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(legacyOutputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(legacyPanelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(legacySendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(legacyInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(legacyStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        legacyPanelLayout.setVerticalGroup(
            legacyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, legacyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(legacyOutputField, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(legacyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(legacyInputField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(legacySendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(legacyStartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        legacyStartButton.getAccessibleContext().setAccessibleName("legacySend");

        tabbedPane.addTab("Legacy", legacyPanel);

        mainMenu.setBackground(new java.awt.Color(0, 0, 0));
        mainMenu.setForeground(new java.awt.Color(255, 255, 255));

        titleLabel.setAlignment(1);
        titleLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 150, 0));
        titleLabel.setName("Title"); // NOI18N
        titleLabel.setText("Netra14's Afk Doctor Bot");

        outputField.setBackground(new java.awt.Color(50, 50, 50));
        outputField.setForeground(new java.awt.Color(0, 150, 0));

        runButton.setBackground(new java.awt.Color(0, 150, 0));
        runButton.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        runButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        runButton.setLabel("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(runButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputField, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        runButton.getAccessibleContext().setAccessibleName("runBot");

        tabbedPane.addTab("Main Menu", mainMenu);

        instructionsPanel.setBackground(new java.awt.Color(0, 0, 0));

        instructionLabel.setForeground(new java.awt.Color(255, 255, 255));
        instructionLabel.setText("Instructions - ");

        javax.swing.GroupLayout instructionsPanelLayout = new javax.swing.GroupLayout(instructionsPanel);
        instructionsPanel.setLayout(instructionsPanelLayout);
        instructionsPanelLayout.setHorizontalGroup(
            instructionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructionsPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(instructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(997, Short.MAX_VALUE))
        );
        instructionsPanelLayout.setVerticalGroup(
            instructionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructionsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(instructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(588, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Instructions", instructionsPanel);

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Settings", settingsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        // TODO run the doctor bot
    	if (runButton.getLabel().equals("Run")) {
    		runButton.setLabel("Stop");
    		runButton.setBackground(new Color(0xFFCC0000));
    	} else {
    		runButton.setLabel("Run");
    		runButton.setBackground(new Color(0xFF009900));
    	}
    }//GEN-LAST:event_runButtonActionPerformed
    // Legacy Methods ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
    Thread bot;
    AfkDoctor legacyBot;
    public void runLegacyCode() {
        // TODO open thread of AFKDoctor Main
        // TODO End main bot if it is going
        legacyBot = new AfkDoctor(legacyOutputField);
        bot = new Thread(() -> {
                //legacyOutputField.append("\nDEBUG: Thread Call Flag");
                AfkDoctor.begin(legacyBot); 
        });
        bot.start();
    }
    public void endLegacyCode() {
        try { bot.interrupt(); } catch (Exception e) {}
        legacyBot.endRoutine();
    }
    private void legacyInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legacyInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_legacyInputFieldActionPerformed

    private void legacyStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legacyStartButtonActionPerformed
        if (legacyStartButton.getLabel().equals("Start")) {
            legacyStartButton.setLabel("End");
            runLegacyCode();
        } else {
            legacyStartButton.setLabel("Start");
            endLegacyCode();
        }
    }//GEN-LAST:event_legacyStartButtonActionPerformed

    private void legacySendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legacySendButtonActionPerformed
        legacyOutputField.append("\n" + legacyInputField.getText());
        legacyBot.setNextScan(legacyInputField.getText());
        legacyInputField.setText("");
    }//GEN-LAST:event_legacySendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
        	e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KillerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label instructionLabel;
    private javax.swing.JPanel instructionsPanel;
    private javax.swing.JPanel jPanel2;
    private java.awt.TextField legacyInputField;
    private java.awt.TextArea legacyOutputField;
    private javax.swing.JPanel legacyPanel;
    private java.awt.Button legacySendButton;
    private java.awt.Button legacyStartButton;
    private javax.swing.JPanel mainMenu;
    private java.awt.TextArea outputField;
    private java.awt.Button runButton;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private java.awt.Label titleLabel;
    // End of variables declaration//GEN-END:variables
}